
    export const sellers=[
        {  
            id:1,
            img:"https://cdn.pixabay.com/photo/2017/01/06/17/49/honey-1958464_960_720.jpg",
            name:'HONEY',
            desc:"In the area where you want to begin this business, get involved with bees and learn about them practically. Take good honey bee farming training.Suppose the farmer or entrepreneur has no prior experience working with bees. In that case, they should work with local entrepreneurs or farmers to get all the honey bee farming process information. After this, the entrepreneur should make an effective plan for using the equipment and selling the products.While making a bee farming business plan, set realistic goals only and start from a small level in the beginning phase; when you gain some experience in the honey business in India, you can also think about big projects. However, what equipment can be used and what species of bees should be reared in this project depends on the local situation. Entrepreneurs or farmers doing honey bee farming project should identify a local agent to sell products in advance. In addition, ayurvedic pharmaceutical companies, local bakers, candy makers and many more can be big customers for honey."
        },
        {
            id:2,
            img:"https://parasdairy.com/blog/wp-content/uploads/2021/09/Toned-milk.jpg",
            name:'TONED BUFFALO MILK',
            desc:"Animals fed only on dry fodder may be provided Urea Molasses Mineral Block as a supplement to the diet, depending upon its availability.For body maintenance and higher efficiency of milk production, compound cattle feed bypass protein feed should also be given Minerals are essential for all metabolic functions of the body animals ration should be supplemented with area specific mineral mixture.Heat Stress indicates all high temperature related stress, which induces thermoregulatory changes in cattle. During the extreme hot humid or hot dry weather, this thermoregulatory capability of cattle to dissipate heat by sweating and panting is compromised and heat stress occurs.Though indigenous breeds of cattle are more thermo-tolerant, crossbred and exotic breeds of cattle are highly sensitive to heat stress.  Buffaloes are more prone to this owing to their black skin that absorbs more solar radiations and fewer sweat glands (only 1/6th that of cattle), compromising heat dissipation through evaporative heat loss."
        },
        {
            id:3,
            img:"https://img.freepik.com/free-photo/close-up-box-with-vegetables-hands-mature-man_329181-4600.jpg?w=996&t=st=1680072217~exp=1680072817~hmac=6b88c3d658af018eeca78fd9ae27db259f6bc69eee04e55481e3eb89e3b93ee0",
            name:'GREEN VEGETABLE',
            desc:"Method of SowingSpinach- The distance from the queue to the line should be 20 cm and the distance from plant to plant should be 3 to 4 cm. Methi- The distance from the queue to queue should be 20 to 25 cm and the distance from plant to plant should be 3 to 4 cm.Chhoti Chaulai- The distance from the queue to queue should be 20 to 25 cm and the distance from plant to plant should be 4 to 5 cm.Badi Chaulai- The distance from the queue to queue should be 30 to 35 cm and the distance from plant to plant should be 4 to 5 cm.Weed Control For good yield, remove weeds from the beds periodically. With this, the growth of the plant is also good. At the same time, the outbreak of insects is also less.IrrigationIn green leafy vegetables, irrigation should be done as per requirement. During this time, it should be kept in mind that seeds should not be sown in dry soil and irrigated immediately after sowing. This prevents germination of seeds properly. HarvestingFirst harvesting of vegetables should be done after 25 to 30 days. After that, harvesting continued for 15 to 20 days. "
        },
        {
            id:4,
            img:"https://cdn.britannica.com/89/140889-050-EC3F00BF/Ripening-heads-rice-Oryza-sativa.jpg",
            name:'BASMATI RICE',
            desc:"To obtain satisfactory yield of Basmati varieties the following package of practices arerecommended for adoption : Important Points : * Restrict to timely sowing and transplanting schedule of basmati varieties for better quality rice. * Avoid mixing of varieties. * Monitor the insect-pest population/damage and use recommended control measures.* All the basmati/aromatic varieties, especially Pusa Basmati 1121 are susceptible to foot rotdisease. Use only disease free seed.* Use seed treatment to avoid seed borne diseases. Climatic Requirements :Like semi-dwarf rice varieties, Basmati varieties require prolonged sunshine, high humidityand assured water supply. Basmati varieties with superior cooking and eating characteristics canbe produced if the crop matures in relatively cooler temperature. The high temperature duringgrain filling period reduces the cooking and eating quality features of basmati rice like kernel elongation and non-stickiness of cooked rice.Rotations:(i) Basmati rice-Wheat*/Sunflower(ii) Basmati rice-Wheat-Sathi maize/Summer moong. (iii) Basmati rice-Mentha (iv) Basmati rice-Berseem (seed)(v) Basmati rice-celery-bajra (fodder)"
        },
        {
            id:5,
            img:"https://cdn.shopify.com/s/files/1/1857/6931/articles/millets_new_featured_image_1578x.jpg?v=1637563748",
            name:'MILLETS',
            desc:"Millets are drought tolerant crops and are predominantly grown as rainfed crops in Kharif and on conserved moisture in Rabi. •	 Based on the availability of water, one life saving irrigation and 3 to 4 irrigations at critical stages needs to be given. •	 Thus, the field should have proper access to irrigation source to provide at least one life saving irrigation during long spell moisture stress condition. •	 Well drain soils should be preferred to avoid water logging problem.1) Providing isolation to prevent cross fertilization or Pollen contamination.2) Roguing of seed fields to maintain uniformity.3) Periodic testing of varieties for genetic purity: Field inspection and approval of the crop at critical stages for verification of genetic purity, detection of mixtures, weeds and seed borne diseases.Good Agricultural Practices in Millets 4) Growing adapted areas only to avoid genetic shifts in the variety. 5) Certification of seed crops to maintain genetic purity and quality.6) Adopting generation system of seed multiplication. 7) Growing of samples with authentic stocks or grow-out test."
    
        },
        {
            id:6,
            img:"https://post.medicalnewstoday.com/wp-content/uploads/sites/3/2022/01/mangoes_what_to_know_732x549_thumb-732x549.jpg",
            name:'MANGO',
            desc:"5.4.1        Planting Material Mango can be propagated from seed or propagated vegetatively. Plants are generally propagated vegetatively by using several techniques like veneer grafting, inarching and epicotyl grafting etc. 5.4.2        Planting Season Planting is usually done in the month of July-August in rainfed areas and during February-March in irrigated areas.  In case of heavy rainfall zones, planting is taken up at the end of rainy season.5.4.3        Spacing The planting distance is 10m. x 10m. and 12m. x 12m. in dry and moist zones respectively.  In the model scheme, a spacing of 8m. x 8m. with a population of 63 plants per acre has been considered which was observed to be common in areas covered during a field study.5.5              Training of Plants Training of plants in the initial stages of growth is very important to give them a proper shape specially in cases where the graft has branched too low.   5.6               Nutrition Fertilizers may be applied in two split doses , one half immediately after the harvesting of fruits in June/July and the other half in October, in both young and old orchards followed by irrigation if there are no rains. Foliar application of 3 % urea in sandy soils is recommended before flowering. "
        },
        {
            id:7,
            img:"https://img.etimg.com/thumb/width-1200,height-900,imgsize-176599,resizemode-1,msid-83390496/small-biz/trade/exports/insights/indias-booming-corn-exports-amid-global-rally-ease-supply-worries.jpg",
            name:'CORN',
            desc:"During the initial stage, the growth of the maize plants is suppressed by weeds. Weeding may be done between the rows with bullock or tractors drawn implements, whereas the weeding within the row is done by hand. Two or three weedings may be necessary, following which the crop is earthed up to provide for better standability. For obtaining high yield, the maize crop should be heavily manured. Twenty five to thirty cartloads of farmyard manure or compost should be ploughed into the soil before the sowing. For hybrid and composite varieties of maize, 100-120 kg of nitrogen, along with 60 kg of P2O5 and 40 kg of K2O per hectare, is recommended. In regions with about 60 cm of well distributed rainfall during the growing season, any additional irrigation is not necessary. Inadequate soil moisture during flowering and poet flowering particularly during the grain filling period will markedly reduce the yield.The maize crop sown for grain is harvested when the grains are nearly dry and do not contain more than 20 per cent moisture. The appearance of the plant may be misleading, particularly in the case of high yielding hybrids and composites whose grains are dry, while the stalk and leaves may be still green."
        },
        {
            id:8,
            img:"https://thumbs.dreamstime.com/z/marine-fishery-3776454.jpg",
            name:'FISHERY',
            desc:"Intensive pond culture with supplementary feeding and aeration (10–15 tonnes/ha/yr) Composite carp culture (4–6 tonnes/ha/yr) Weed-based carp polyculture (3–4 tonnes/ha/yr)Integrated fish farming with poultry, pigs, ducks, horticulture, etc. ...Pen culture (3–5 tonnes/ha/yr) Cage culture (10–15 kg/m2/yr) Brackish water aquaculture involves breeding of fish that habitat the sea like sea bass, grey mullet, tiger shrimp and mud crabs. It is practiced in States like West Bengal, Andhra Pradesh, Kerala and Goa. Fish farmers use a mixture of oil cakes, rice bran, locally available snail, clam or mussel meat and buffalo meat to feed the fish.The farmer should monitor the level of water hardness, acidity/ alkalinity, contaminants, industrial chemicals and pesticides in the water. He should also see that there is enough dissolved oxygen in the water for the survival of aquatic life. Common chemicals used in aquaculture are EDTA (ethylenediaminetetraacetate) disodium salt for removing water hardness, sodium nitrate for algae formation, ammonium chloride for boosting water fertility and formaldehyde, a bactericide."
        },
        {
            id:9,
            img:"",
            name:'PULSES',
            desc:" The most potential technologies in pulse production include improved crop establishment and management practices, integrated soil fertility and pest management practices, etc. which enhance not only the productivity and profitability but also warrants environmental and social sustainability besides nutritional security. Extra early, suitable for double cropping,escapes droughtVL 1 Arhar For hilly areas and intercropping in NWHimalayasAzad Resistant to sterility mosaicNarendra Arhar 1 Resistant to sterility mosaic and tolerant towilt, pod borerICPH 8 Hybrid, 30% more yield than UPAS 120PPH 4 Short durationPusa 991, 992 Wilt and sterility mosaic resistantPusa 2001, 2002 Phytophthora blight tolerantTJT 501 Sterility mosaic and wilt resistant Like other plants, herbs can become stressed in windy or exposed sites. Growing herbs in beds near the house or next to other buildings or walls provides a warm, sheltering microclimate and increases a gardener's chances of success with tender perennials like rosemary, which is hardy only to Zone 8."
        },
        {
            id:10,
            img:"https://www.thespruceeats.com/thmb/GFvSucJcAVCi2WNtsmLh8I3Sbkw=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/various-fresh-herbs-907728974-cc6c2be53aac46de9e6a4b47a0e630e4.jpg",
            name:'HERBS',
            desc:"Most herbs thrive in full sun (six or more hours of direct sunlight per day). If you have a garden that receives less sun, choose herbs that don't need as much.Like other plants, herbs can become stressed in windy or exposed sites. Growing herbs in beds near the house or next to other buildings or walls provides a warm, sheltering microclimate and increases a gardener's chances of success with tender perennials like rosemary, which is hardy only to Zone 8. Even if you grow rosemary in containers and bring it indoors for the winter, it's still a good idea to set it out in a sunny, sheltered area."
        },
        {
            id:10,
            img:"https://tradebrains.in/features/wp-content/uploads/2022/06/Wheat-Cover-Image-1080x675.jpg",
            name:'WHEAT',
            desc:"Some Useful Hints Do'sspray the herbicides, both pre and post emergence, when there is sufficient moisture in the soil. SSpray the post-emergence herbicides when Phalaris minor is at 2-3 leaf stage. Spray on clear and sunny days only when the leaves are dry.Use only flat fan nozzle especially for Fenoxaprop.Remove Phalaris minor before seed setting and use as fodder. Ensure complete coverage of the field.  Don'tsDo not use Sulfosulfuran in mixed cropping system of wheat and mustard or other crops. Never apply these post emergence herbicides by mixing with sand, urea or soil. Do not mix Clodinafop and Fenoxaprop with 2,4-D The major diseases of wheat in India are, three rusts - leaf, yellow and stem rust, Karnal bunt, foliar blights, powdery mildew and loose smut. Diseases of limited importance include head scab, foot rot and flag smut; these diseases though of lesser importance, may be important in certain pockets Weed control Both Grassy and Broad Leaved Sulfosulfuran @ 25.0g a.i./ha in 250-300 liters of water /ha.Metribuzin @ 175 g a.i./ha in at least 500 liters of water /ha.A mixture of Sulfosulfuran at 25g/ha and metsulfuron methyl @ 4 g/ha in 250-300 liters water /ha.Combination of 2,4-0 and isoproturon can also be used for the control of mixed weed population in resistance free area. Only Grassy WeedsClodinafop @ 400 g/ha (60g a.i./ha) in 250-300 liters of water / ha. Fenoxaprop-ethyl @ 80-120g a.i./ha in 250-300 liters of water / ha."
        },
        {
            id:10,
            img:"https://img1.exportersindia.com/product_images/bc-full/2019/3/6141893/turmeric-powder-1552034171-4776619.jpeg",
            name:'TUMERIC',
            desc:"Curing Fresh turmeric is cured for obtaining dry turmeric. The fingers are separated from mother rhizomes. Mother rhizomes are usually kept as seed material. Curing involves boiling of fresh rhizomes in water and drying in the sun.In the traditional method of curing, the cleaned rhizomes are boiled in water just enough to immerse them. Boiling is stopped when froth comes out and white fumes appear giving out a typical odour. The boiling should last for 45-60 minutes when the rhizomes turn soft. The stage at which boiling is stopped largely influences the colour and aroma of the final product. Over cooking spoils the colour of the final product while under-cooking renders the dried product brittl Drying The cooked fingers are dried in the sun by spreading them in 5-7 cm thick layers on bamboo mats or drying floor. A thinner layer is not desirable, as the colour of the dried product may be adversely affected. During night time, the rhizomes should be heaped or covered with material which provides aeration.Dried turmeric has a poor appearance and a rough dull outer surface with scales and root bits. The appearance is improved by smoothening and polishing the outer surface by manual or mechanical rubbing.Colouring The colour of the processed turmeric influences the price of the produce. For an attractive product, turmeric powder (mixed with little water) may be sprinkled during the last phase of polishing."
        },
    
]